### ISSUE TITLE
Cannot download Activiti Plugin from repository

### ISSUE THREAD

**Issue by piotrkorlaga** [Activiti/Activiti-Designer#48]
I'd like to install Eclipse plugin according to docs: (http://docs.alfresco.com/5.1/tasks/wf-install-activiti-designer.html)  Unfortunately Activiti plugin is not available here: http://activiti.org/designer/update/

Any idea how can I install it?

**Comment by rohitbatta** [comment]
Hi @piotrkorlaga ,

You can refer following blogs to download compiled plugin for eclipse activiti.
[https://github.com/Activiti/Activiti-Designer/issues/47#issuecomment-269607593](https://github.com/Activiti/Activiti-Designer/issues/47#issuecomment-269607593)

Another detail discussions are on following threads:
[https://community.alfresco.com/thread/227353-activiti-eclipse-plugin](https://community.alfresco.com/thread/227353-activiti-eclipse-plugin)
[http://stackoverflow.com/questions/41346224/installation-of-custom-eclipse-plug-in-available-at-github](http://stackoverflow.com/questions/41346224/installation-of-custom-eclipse-plug-in-available-at-github)

**Comment by piotrkorlaga** [comment]
thanks @rohitbatta 
Now also https://www.activiti.org/designer/update/ is available

**Comment by roldevg** [comment]
Hi! I have opened a [pull request](https://github.com/Activiti/Activiti-Designer/pull/58) for this problem.
