### ISSUE TITLE
When plan to  supported for eclipse neon? 

### ISSUE THREAD

**Issue by zrweng** [Activiti/Activiti-Designer#50]
When plan to  supported for neon

**Comment by gaigeshen** [comment]
When plan to supported for neon ?

**Comment by n0mer** [comment]
@gaigeshen i think, @zrweng is asking are there any plans to have support for eclipse neon.

Here is quote from graphiti downloads page https://eclipse.org/graphiti/download.php :

> The latest milestone versions of Graphiti 0.14.0 (Oxygen release train version) are available for download from here. They will run against Eclipse 4.6 (Neon) and Eclipse 4.7 (Oxygen)

**Comment by n0mer** [comment]
from https://github.com/Activiti/Activiti-Designer/blob/master/org.activiti.designer.parent/pom.xml :

* graphiti 0.10.1 -> for eclipse platform [3.8) ("juno")
* graphiti 0.10.2 -> 4.3 "kepler"
* graphiti 0.11.4 -> 4.4 "luna"

**Comment by gaigeshen** [comment]
No neon version of activiti ?

**Comment by gaigeshen** [comment]
I found a pull request, https://github.com/Activiti/Activiti-Designer/pull/44
