### ISSUE TITLE
Is a dead project ?

### ISSUE THREAD

**Issue by Zorin95670** [Activiti/Activiti-Designer#67]
There are no commit on project until 2016, I think project is dead...

Someone of a dev teams can confirm this or not ?

**Comment by mteodori** [comment]
Yes, as you have correctly guessed from the last updated date, modeling for latest Activiti and Activiti Cloud is now on the web based http://github.com/Alfresco/alfresco-modeling-app

**Comment by mteodori** [comment]
I am going to add a DEPRECATED notice and archive the project to make it more clear
